on: [push]

jobs:
  test_yq_job:
    runs-on: ubuntu-latest
    name: use yq
    steps: 
    - uses: actions/checkout@v2
    - name: YQ extract path from filename 
      id: yq
      uses: jduimovich/action-yq@master
      with:
        file: 'namespace.yaml'
        path: 'metadata.name'
    # Use the output from the `yq` step
    - name: Print the namespace extracted 
      run: echo "The result was ${{ steps.yq.outputs.result }}"

